#!/usr/bin/env python3
"""Cross-checks every HTTP call in swift/Packages/KomeliaKit/Sources/KomgaRemote against the
Komga OpenAPI snapshot (fixtures/komga/openapi.json) and writes docs/wire-format.md.

Usage: tools/wire_contract_check.py   (exit code 1 if any endpoint is missing from the spec)
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "swift/Packages/KomeliaKit/Sources/KomgaRemote"
SPEC = ROOT / "fixtures/komga/openapi.json"
OUT = ROOT / "docs/wire-format.md"

CALL = re.compile(
    r'(?:request|jsonRequest)\(\s*\.(get|post|put|patch|delete)\s*,\s*"([^"]+)"'
    r'|(?:fetchBytes|sibling|scoped|activity)\(\s*"([^"]+)"'
    r'|(?:uploadThumbnail)\(\s*path:\s*"([^"]+)"'
)
FUNC = re.compile(r'(?:public\s+)?func\s+(\w+)')
TYPE = re.compile(r'public (?:struct|final class) (\w+)')


def normalize(path: str) -> str:
    return "/" + re.sub(r"\\\([^)]*\)", "{}", path).lstrip("/")


def spec_index(spec):
    index = {}
    for path, ops in spec["paths"].items():
        key = re.sub(r"\{[^}]+\}", "{}", path)
        for method in ops:
            index[(method.upper(), key)] = path
    return index


def collect():
    rows = []
    for file in sorted(SOURCES.rglob("*.swift")):
        current_type, current_func = "", ""
        for line in file.read_text().splitlines():
            if m := TYPE.search(line):
                current_type = m.group(1)
            if m := FUNC.search(line):
                current_func = m.group(1)
            for m in CALL.finditer(line):
                method, path, bytes_path, upload_path = m.groups()
                if bytes_path:
                    method, path = "get", bytes_path
                elif upload_path:
                    method, path = "post", upload_path
                rows.append((current_type, current_func, method.upper(), normalize(path)))
    return rows


def main():
    spec = json.loads(SPEC.read_text())
    index = spec_index(spec)
    rows = collect()
    missing = []
    lines = [
        "# Komga wire format — contract table",
        "",
        "Generated by `tools/wire_contract_check.py` (plan Phase 0). Source of truth: `GET /v3/api-docs` of the",
        f"fixture server (Komga **{spec['info'].get('version', '?')}**, snapshot in `fixtures/komga/openapi.json`),",
        "cross-checked against every HTTP call in `KomgaRemote`. The Kotlin library (`komga-client 0.11.0`) was",
        "used for method semantics; its source is cloned (read-only) at `reference/komga-client`.",
        "",
        "| Swift type | Operation | Method | Path | In OpenAPI |",
        "|---|---|---|---|---|",
    ]
    for type_, func, method, path in rows:
        found = index.get((method, path))
        if path.startswith("/actuator") or path.startswith("/sse") or path == "/api/logout":
            status = "n/a (not in api-docs)"
        elif found:
            status = "✅"
        else:
            status = "❌"
            missing.append(f"{method} {path}")
        lines.append(f"| `{type_}` | `{func}` | {method} | `{found or path}` | {status} |")

    lines += [
        "",
        f"**{len(rows)} HTTP operations**, {len(missing)} missing from the spec.",
        "",
        "## Verified server behaviour (Komga 1.27.0 fixture)",
        "",
        "- JSON timestamps: ISO-8601 with and without fractional seconds / `Z` or `+00:00` offset.",
        "- `LocalDate` fields (`releaseDate`) are `yyyy-MM-dd`.",
        "- `Page<T>`: Spring page; `pageable` may be the string `\"INSTANCE\"` for unpaged results → decoded leniently.",
        "- `POST /api/v1/{books,series}/list` ignores `unpaged`; paging via `page`/`size`/`sort` query params.",
        "- Search conditions: single-key objects (`{\"seriesId\":{\"operator\":\"is\",\"value\":\"…\"}}`), groups `allOf`/`anyOf`.",
        "  The kotlinx polymorphic `type` discriminator is not needed and not sent.",
        "- `sort` is repeatable (`sort=a,asc&sort=b,desc`). The Kotlin client concatenated orders into one value (bug, fixed).",
        "- `GET /api/v1/{collections/{id}/series, readlists/{id}/books}` take repeated `author=name,role`;",
        "  the Kotlin client sent `authors=` (ignored by the server — bug, fixed).",
        "- `GET /api/v1/books/{id}/file` **ignores `Range`** → download resume is impossible; retries restart.",
        "- Genres are returned lowercased.",
        "- Login: `GET /api/v2/users/me?remember-me=true` with Basic auth sets `KOMGA-SESSION` + `komga-remember-me`",
        "  (`Path=/`); subsequent cookie-only requests are authenticated. Unauthenticated → 401.",
        "- SSE: `GET /sse/v1/events` (`text/event-stream`), event name = Kotlin class name, data = JSON payload.",
        "- `GET /api/v1/books/{id}/thumbnail` for an unknown id → 404 (mapped to `nil`).",
    ]
    if missing:
        lines += ["", "## ❌ Missing from spec", ""] + [f"- `{m}`" for m in missing]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{len(rows)} operations, {len(missing)} missing -> {OUT.relative_to(ROOT)}")
    for m in missing:
        print("  missing:", m)
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
